// Service worker registration (offline app shell + wasm + immutable blob cache, generated by
// vite-plugin-pwa → /sw.js) with an explicit "update available" prompt, and the install prompt.
// Registered by hand (no workbox-window dependency): Workbox's generated SW listens for
// { type: 'SKIP_WAITING' } messages.
import { useSyncExternalStore } from 'react'
import { toast } from '../ui'
import { t } from '../i18n'

interface BeforeInstallPromptEvent extends Event {
  prompt(): Promise<void>
  userChoice: Promise<{ outcome: 'accepted' | 'dismissed' }>
}

let deferred: BeforeInstallPromptEvent | null = null
const listeners = new Set<() => void>()
const notify = () => listeners.forEach((l) => l())
const UPDATE_CHECK_MS = 60 * 60 * 1000

function promptUpdate(worker: ServiceWorker): void {
  toast(t('pwa.updateTitle', 'A new version of CadSandbox is available'), {
    duration: Infinity,
    action: {
      label: t('pwa.reload', 'Reload'),
      onClick: () => {
        reloadOnActivate = true
        worker.postMessage({ type: 'SKIP_WAITING' })
      },
    },
  })
}

let reloadOnActivate = false

async function registerServiceWorker(): Promise<void> {
  const reg = await navigator.serviceWorker.register('/sw.js', { scope: '/' })
  if (reg.waiting && navigator.serviceWorker.controller) promptUpdate(reg.waiting)
  reg.addEventListener('updatefound', () => {
    const worker = reg.installing
    if (!worker) return
    worker.addEventListener('statechange', () => {
      if (worker.state !== 'installed') return
      if (navigator.serviceWorker.controller) promptUpdate(worker)
      else toast.success(t('pwa.offlineReady', 'CadSandbox is ready to work offline'))
    })
  })
  navigator.serviceWorker.addEventListener('controllerchange', () => {
    if (!reloadOnActivate) return
    reloadOnActivate = false
    window.location.reload()
  })
  setInterval(() => void reg.update().catch(() => undefined), UPDATE_CHECK_MS)
}

export function setupPWA(): void {
  if (typeof window === 'undefined') return
  window.addEventListener('beforeinstallprompt', (e) => {
    e.preventDefault()
    deferred = e as BeforeInstallPromptEvent
    notify()
  })
  window.addEventListener('appinstalled', () => {
    deferred = null
    notify()
  })
  if (!('serviceWorker' in navigator) || import.meta.env.DEV) return
  window.addEventListener('load', () => {
    registerServiceWorker().catch((err: unknown) => console.warn('[pwa] service worker registration failed', err))
  })
}

function subscribe(cb: () => void): () => void {
  listeners.add(cb)
  return () => listeners.delete(cb)
}

/** "Install app" support (Chromium). Safari users install via the share sheet. */
export function useInstallPrompt(): { canInstall: boolean; install: () => Promise<boolean> } {
  const canInstall = useSyncExternalStore(
    subscribe,
    () => deferred !== null,
    () => false,
  )
  return {
    canInstall,
    install: async () => {
      if (!deferred) return false
      const ev = deferred
      deferred = null
      notify()
      await ev.prompt()
      return (await ev.userChoice).outcome === 'accepted'
    },
  }
}
